---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readr)
library(patchwork)
```


```{r}
nade <- read_csv('training_data/nade.csv', col_types = cols(
  mode = col_factor(),
  epoch = col_factor(),
  loss = col_double()
))
nade
```

```{r}
nade %>%
  ggplot() +
  geom_line(aes(epoch, loss, group=mode), color='#619CFF') +
  geom_label(aes(epoch, loss, label=loss), color='#619CFF') +
  scale_x_discrete(expand=expansion(mult=c(0.1,0.1))) +
  scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) +
  ylab('Average negative log-likelihood (NLL)') +
  xlab("Epoch") +
  ggtitle('NADE performance', subtitle='Average negative log-likelihood evolution per epoch') +
  facet_grid(mode~.) +
  theme_light() +
  theme(plot.subtitle = element_text(color='gray60'))
```
```{r}
ggsave('plots/nade.png', device='png', width = 7, height = 4)
```

```{r}
pixel <- read_csv('training_data/pixel.csv', col_types = cols(
  mode = col_factor(),
  epoch = col_factor(),
  loss = col_double()
))
pixel
```
```{r}
pixel %>%
  ggplot() +
  geom_line(aes(epoch, loss, group=mode), color='#619CFF') +
  geom_label(aes(epoch, loss, label=round(loss)), color='#619CFF', size=3) +
  scale_x_discrete(expand=expansion(mult=c(0.1,0.1))) +
  scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) +
  ylab('Average negative log-likelihood (NLL)') +
  xlab("Epoch") +
  facet_grid(mode~.) +
  ggtitle('PixelRNN performance', subtitle='Average negative log-likelihood evolution per epoch') +
  theme_light() +
  theme(plot.subtitle = element_text(color='gray60'))
```
```{r}
ggsave('plots/pixel.png', device='png', width = 7, height = 4)
```

```{r}
transformer <- read_csv('training_data/transformer.csv', col_types = cols(
  mode = col_factor(),
  epoch = col_factor(),
  loss = col_double()
))
transformer
```
```{r}
transformer %>%
  ggplot() +
  geom_line(aes(epoch, loss, group=mode), color='#619CFF') +
  geom_label(aes(epoch, loss, label=round(loss)), color='#619CFF', size=3) +
  scale_x_discrete(expand=expansion(mult=c(0.1,0.1))) +
  scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) +
  ylab('Average negative log-likelihood (NLL)') +
  xlab("Epoch") +
  facet_grid(mode~.) +
  ggtitle('Transformer performance', subtitle='Average negative log-likelihood evolution per epoch') +
  theme_light() +
  theme(plot.subtitle = element_text(color='gray60'))
```

```{r}
ggsave('plots/transformer.png', device='png', width = 7, height = 4)
```

